# Custom Language File for Launcher Customizer

[ejs.app]
title = "The Dragon Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/SuperLexou01/TheDragonLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/channel/UCkQF-6LCSOj-6_KqiG44eJA"
mediaDiscordURL = "https://discord.gg/WmPzWgtK"

[ejs.settings]
sourceGithubLink = "https://github.com/SuperLexou01/TheDragonLauncher"
supportLink = "https://github.com/SuperLexou01/TheDragonLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO THE DRAGON"
welcomeDescription = "This is the official launcher of The Dragon, a server PVP faction server based on the 'ice and fire' mod where you can catch and ride dragons."
welcomeDescCTA = "Adventure and dragons are here. Sshh don't wake them up or it's gonna be intense."
